@user_token=eyJhbGciOiJSUzM4NCJ9.eyJzdWIiOiJyb2JlcnRAZW1haWwuY29tIiwiaXNzIjoiREFUMTUyLUxlY3R1cmVyQFRET1kiLCJmaXJzdG5hbWUiOiJSb2JlcnQiLCJsYXN0bmFtZSI6IklzYWFjIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3MjkyNTI1NDksImV4cCI6MTcyOTY4NDU0OX0.rN2W4kTM0Ne_YybPWqnxlj1QZ8wYa0_vvtyKF2YpaaiGXCo12bpzxP-F4aVZIUWuKiuJ0RZSeR_A3Rpbng_SyHUAXg_NO0mg-zqG7rYec5oDw6M8QsZ57ZxGjGoJhC3Od55H2chhDgSm6TWqBscLRNZOsbEpFcnUMfsLi_i-KIN4K196xOAJXFU_uDnWm46-iwvjMsvO1NuU-y3lr0va89KmyTAAQJVInoXnVLw1ZDs3JJMaOFGyc0I4GUvxDhMhMPTOJZAxUN1w5gxf07QmZTw2WG5N3XOl0wYGp2DZd-jAXSYIkK-DGhK31_4KifaxoKrzXMl_Fw36W6vTIdSQoRTw5l1_n1M-JlC5fZC-gEychozGcbJgLgdXgKdF9Psj5NxkuwdhpvVA3Xv_XkSkICAGCLUh6K31arkYY3rVSyVrY00UmfyyDJNZDNlfTxOgKUBeHNmse-UtBExxhHHXPoe9skhswV4JQAGv0mk1WLCXNDqi9wV1eW8_h7syE83v
@admin_token=eyJhbGciOiJSUzM4NCJ9.eyJzdWIiOiJiZXJpdEBlbWFpbC5jb20iLCJpc3MiOiJEQVQxNTItTGVjdHVyZXJAVERPWSIsImZpcnN0bmFtZSI6IkJlcml0IiwibGFzdG5hbWUiOiJKw7hyZ2Vuc2VuIiwicm9sZXMiOlsiQURNSU4iLCJTVVBFUl9BRE1JTiIsIlVTRVIiXSwiaWF0IjoxNzI5MjUyNTQ5LCJleHAiOjE3Mjk2ODQ1NDl9.hx-oPcpBQBmMNWG3KfMFiedbf1tyl2SukDqDy9J41ciM-nzr8bEOoUUzV14Ghlad5SHk2-fHfjSaO7uq5MMILeb6fCAlEzn8K_P3iyC-6XCRTmQVxnISuIvLljTB0sPUClvpX3_XxdU9xwEXrkBTjFf7yKpjLA8LioNQV8owRt4Qodg-8YrA3SsSZ-TxswIpzlBqlCYyL-cwHlT96vXxKt5NJduYKVk8b2nSRo8TgFMXxVqwU0THGpBZqZumJ3U7-TSSz4WArpQ5p_htqFqrqDUHsM_D2kPa_o6PppPafA7qcVWY4sKEve9qt1tmPfW5KgdH-VPLdqT3z2deFRXBQ5NHyE6D_vz5ljHKdj5IKgASZaqsMRg1XiPRubLWIfJtVvYc04hEIJtDOXi-iEDkqYQc2h_EKDVfhEf8p2zx714_Z0i6C3qwdjgR7n5qSajJSSE0JX0qVtABkR28-oy7dbUnU7_jsc7GJQQbtmJRwc7Yj8l8JCx8VlvZRwg8elvf

POST localhost:8090/elibrary/api/v1/users/1/orders
Accept: application/json
Content-Type: application/json

{
  "isbn": "abcde12344",
  "expiry": "2024-10-17"
}
###

GET localhost:8090/elibrary/api/v1/orders/4
Accept: application/json
###

GET localhost:8090/elibrary/api/v1/orders?expiry=2024-11-10&page=1&size=2
Accept: application/json
###

GET localhost:8090/elibrary/api/v1/users
Accept: application/json
Authorization: Bearer {{user_token}}
###

GET localhost:8090/elibrary/api/v1/orders/1
Accept: application/json
Authorization: Bearer {{user_token}}

###

POST localhost:8090/elibrary/api/v1/users/2/orders
Accept: application/json
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "isbn":"rstuv1540",
  "expiry":"2024-10-30"
}
